name: 'Setup Screenshot Tools'
description: 'Install ImageMagick and perceptualdiff for visual regression testing'

runs:
  using: 'composite'
  steps:
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        # imagemagick-6.q16 explicitly listed because the caching action doesn't
        # properly restore this dependency of imagemagick (contains /usr/bin/import)
        # fonts-noto-* for i18n screenshot testing (emoji, CJK characters)
        packages: xvfb imagemagick imagemagick-6.q16 perceptualdiff fonts-noto-color-emoji fonts-noto-cjk
        execute_install_scripts: true

    # The caching action doesn't run post-install scripts that create symlinks
    # See: https://github.com/awalsh128/cache-apt-pkgs-action/issues/110
    - name: Symlink ImageMagick commands
      shell: bash
      run: |
        sudo ln -sf /usr/bin/import-im6.q16 /usr/bin/import
        sudo ln -sf /usr/bin/composite-im6.q16 /usr/bin/composite
